#!/bin/bash
export PATH=/usr/local/bin/:/usr/bin:/bin:$PATH
CUR_PATH=`pwd`
basepath=$(cd `dirname $0`; pwd)
echo $CUR_PATH
echo $basepath
cd $basepath

#ss server start tool

if [[ $1 ]]; then
    LOG=`nohup /usr/sbin/haproxy -f ${1} &> /dev/null & echo $!`
else
    LOG=`nohup /usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg &> /dev/null & echo $!`
fi
# LOG=`nohup python klinetool.py > log.txt 2>&1 & echo $!`
# # LOG="12345"
echo $LOG
OUTSTR=$LOG
echo $OUTSTR > ${basepath}/haproxy_psid.txt
echo 'sserver start'